services:
  nginx:
    container_name: nginx-server
    hostname: nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
  php:
    container_name: php-fpm
    hostname: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
    networks:
      - default
  mysql:
    container_name: mysql-db
    hostname: mysql
    image: mysql:8.3.0
    volumes:
      - ./docker/mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - default
networks:
  default:
    driver: bridge

